language: php

php:
  - '7.2'

install:
  - composer install

script: 
  - mkdir -p build/logs
  - vendor/bin/phpcs --extensions=cls/vba --standard=src/Standards/VBA tests/Test.cls
  - vendor/bin/phpcs --ignore=vendor --standard=PSR2 .

#after_success:
#  - travis_retry php vendor/bin/php-coveralls -v
