#!/bin/bash

python -m pip install antlr4-tools
wget https://raw.githubusercontent.com/Beakerboy/VBA_Tokenizer/ANTLR/vba.g4
antlr4-parse

cd src/ClassModules
for x in *.cls
do
  foo=$(antlr4-parse ../../vba.g4 startRule $x)
  if [[ $foo != "" ]];
  then echo "$x $foo" 1>&2;
    exit 1;
  fi
done
