#!/bin/bash

python -m pip install antlr4-tools
wget https://raw.githubusercontent.com/Beakerboy/VBA_Tokenizer/ANTLR/vba.g4
antlr4-parse

for x in $(find \( -name "*.cls" -o -name "*.bas" -o -name "*.frm" \))
do
  foo=$(antlr4-parse ../../vba.g4 startRule $x)
  echo "$x"
  if [[ $foo != "" ]];
  then echo $foo 1>&2;
    exit 1;
  fi
done
